### ISSUE TITLE
What is the font used in the homepage screenshots

### ISSUE THREAD

**Issue by aseure** [joker-lang/joker-lang.github.io#1]
While I was giving a try to Joker and was wondering which fonts you were using in your [script-showcase-ia.png](https://github.com/joker-lang/joker-lang.github.io/blob/master/images/script-showcase-ia.png) and [linter-showcase-ia.png](https://github.com/joker-lang/joker-lang.github.io/blob/master/images/linter-showcase-ia.png) files.

Project is really great by the way, thanks for open-sourcing it.

**Comment by candid82** [comment]
I think I used InputMono if I remember correctly.

**Comment by aseure** [comment]
Thanks for letting me know!
